### ISSUE TITLE
Error scanning QR Code / error pasting raw LNURL

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnurldevice#25]
Hello together.
Today I encountered an error together with a customer who uses the LNURLDevice extension. We are running 0.11.0 since 06.10.2023. On Version 0.10.10 at Wednesday 04.10.2023 it was working, nor error.

### To reproduce:
* Create LNURLDevice switch
* Scan QR Code
* get error: _Problem processing the LNURL_

The confusing part is, when i decode the LNinvoice i get correct parameters. Server, price etc is correct.

Following i can deliver a few QR Codes + raw LNURL from the effected switch:

**Comment by DoktorShift** [comment]
![IMG_20231008_024056](https://github.com/lnbits/lnurldevice/assets/106493492/02f6eb91-fd52-4e29-9631-e8752ec54265)

LNURL1DP68GURN8GHJ7ARFD4JKXCT5VD5X2U3WD3HXY6T5WVHXGEF0D3H82UNVV3JHV6TRV5HKZURF9AMRYTMVDE6HYMP0VUE9QA3EGFK42DM40FZX54NZF3R4GCT2XETN7URFDC7NZV3XV9KK7ATWWS7NXT3SYEJ82UNPW35K7M3AXGCNQVQVPAMT2

![IMG_20231008_024116](https://github.com/lnbits/lnurldevice/assets/106493492/1be58935-0c08-4bd6-a3d0-1dd15dbf4fac)

LNURL1DP68GURN8GHJ7ARFD4JKXCT5VD5X2U3WD3HXY6T5WVHXGEF0D3H82UNVV3JHV6TRV5HKZURF9AMRYTMVDE6HYMP0VUE9QA3EGFK42DM40FZX54NZF3R4GCT2XETN7URFDC7NZDPXV9KK7ATWWS7NXT3SYEJ82UNPW35K7M3AXGCNQVQ57SMNN

![IMG_20231008_024127](https://github.com/lnbits/lnurldevice/assets/106493492/76d88058-3d07-4ca2-99b0-1d054c291c5b)

LNURL1DP68GURN8GHJ7ARFD4JKXCT5VD5X2U3WD3HXY6T5WVHXGEF0D3H82UNVV3JHV6TRV5HKZURF9AMRYTMVDE6HYMP0VUE9QA3EGFK42DM40FZX54NZF3R4GCT2XETN7URFDC7NYDEXV9KK7ATWWS7NZT3SYEJ82UNPW35K7M3AXGCNQVQFW8GGE

**Comment by AxelHamburch** [comment]
I can confirm it. This is what the server will do if it fails.

![image](https://github.com/lnbits/lnurldevice/assets/84231978/87d38cb8-5cd0-4a73-a5bf-43eabb9f30c2)
![Screenshot_20231008-124812_Breez](https://github.com/lnbits/lnurldevice/assets/84231978/7a9edc72-e77e-496b-8a5e-594234af60da)

**Comment by AxelHamburch** [comment]
Downgrading the LNURLDevice extension to 0.5.5 does not solve the problem either.

**Comment by dni** [comment]
very interesting, i think i found it, the callback attribute adds an object with `_url`: it should be just a string.
![screenshot-1696832496](https://github.com/lnbits/lnurldevice/assets/1743657/2e0824c1-ba1e-4410-82d3-9e804ce5f861)
