### ISSUE TITLE
[BUG] Double action

### ISSUE THREAD

**Issue by dadofsambonzuki** [lnbits/lnurldevice#32]
My devices get fired twice for each invoice paid.

**Comment by motorina0** [comment]
I'm trying to reproduce this. Some questions:
 - was the extension upgraded recently?
 - does the `lnbits` server start with SSL certificates by default (`"--ssl-keyfile=... --ssl-certfile=....` flags)?

Does this reproduce all the time?

**Comment by dadofsambonzuki** [comment]
Yep, we're using Caddy as a reverse proxy.

**Comment by motorina0** [comment]
This should be fixed in 0.12.2

**Comment by dadofsambonzuki** [comment]
Fix confirmed. Thx! 💪
