### ISSUE TITLE
[BUG] Bitcoin switch "Threshold trigger" 

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnurldevice#47]
**Describe the bug**
Since LNbits version 0.12.8 or 0.12.9, there has been a problem with the bitcoinSwitch (also tested with 0.12.10). 
If you modify lines 15-18 in the bitcoinSwitch.ino file, the bitcoinSwitch no longer works. It works with versions 0.12.5 and 0.12.7

**To Reproduce**
1. Only adjust lines 8, 9, and 12 --> bitcoinSwitch works
2. Additionally adjust lines 15, 16, 17, and 18 --> bitcoinSwitch no longer works

**Expected behavior**
If lines 15-18 are adjusted, the bitcoinSwitch should trigger once a threshold is exceeded. Without this adjustment, the bitcoinSwitch only triggers at a predetermined amount.

**Screenshots**
![photo_2024-07-30_00-25-11](https://github.com/user-attachments/assets/1fd5f609-6bb2-494e-a601-d546ff29ded6)

**Desktop:**
- LNNits version: [0.12.9 / 0.12.10 --> not working   0.12.5 and 0.12.7 --> works as intended]
- Database sqlite

**Additional context**
If you use the switch “normally” it works. However, I use the threshold function (line 14-18). So the switch always switches as soon as an amount higher than 1 Sat comes in. 
I have tested it with version 0.12.5 and 0.12.7, where the threshold function works perfectly. So it must be a problem with 0.12.8+

**Comment by arcbtc** [comment]
I think it's more firmware side. 8 can test later, but have you tried configuring via web installer?

**Comment by Camboa** [comment]
Hi,

I usually upload the firmware to the bitcoinSwitch using the Arduino software. I haven't had good experiences with the web installer.

I tested the latest firmware on GitHub as well as a 7-month-old version that I have on my server. The same problem occurs with both. It works with 0.12.7, but not with 0.12.9.

The threshold function worked flawlessly for about 7 months. Since the update to 0.12.9, it no longer works. (I was unable to test it with 0.12.8).

Were you able to test it already?

**Comment by Camboa** [comment]
I was able to test it with version 0.12.8 as well. The error also exists with 0.12.8. 
As soon as something is entered in lines 15-18, the bitcoinSwitch no longer works. 
With version 0.12.7 and below, the 'threshold trigger' works flawlessly. 

Was there something changed in the 0.12.8 update that could be the cause?

**Comment by prusnak** [comment]
Can you try again with 0.12.10?

**Comment by Camboa** [comment]
Thank you for the response.

I just figured out the problem. In line 15 of the bitcoinSwitch.ino file, it states that you need to provide the Wallet ID. This was always the case up until LNbits version 0.12.7. Starting from LNbits 0.12.8 (I tested it with 0.12.9 and 0.12.10), you need to provide the invoice/read key for it to work.

Could someone update the description in line 15 in the bitcoinSwitch.ino file (https://github.com/lnbits/bitcoinswitch/blob/main/bitcoinSwitch/bitcoinSwitch.ino) ?

<img width="933" alt="bitcoinSwitch" src="https://github.com/user-attachments/assets/4d8f1a06-ad82-46b9-ba50-ee58518e803c">




Thanks a lot for the help!

**Comment by prusnak** [comment]
> Could someone update the description in line 15 in the bitcoinSwitch.ino file (https://github.com/lnbits/bitcoinswitch/blob/main/bitcoinSwitch/bitcoinSwitch.ino) ?

Done in https://github.com/lnbits/bitcoinswitch/pull/43
