### ISSUE TITLE
Bug: The variables for the "Switch" do not appear

### ISSUE THREAD

**Issue by AxelHamburch** [lnbits/lnurldevice#6]
When I create a new LNURLDevice instance, preselect everything, and then add the variables for the "Switch", they do not appear. Even if I press +/-.

![2023-04-01 18_18_56-LNbits🍺](https://user-images.githubusercontent.com/84231978/229302951-cc0f0e68-ea6d-4616-ab36-5826881c8535.png)

I must first, after pressing +/- at least 1 time, reselect the "Fiat currency for device" field, or swap currency once, or select ATM or POS once, and then go back to Switch. Then suddenly I see the fields.

![2023-04-01 18_19_17-LNbits🍺](https://user-images.githubusercontent.com/84231978/229302965-0943081d-cda6-46ae-b67f-b54f94593554.png)

The fields for the switch variables only appears if I press +/- at least once and then do another action. If I press five times and then the action, then I have five times the variable fields. 

![2023-04-01 18_29_35-LNbits🍺](https://user-images.githubusercontent.com/84231978/229302996-777c8401-b89e-4228-841b-7e6bd2ed86b2.png)

**Comment by dni** [comment]
can you check the browser console for javascript errors?

**Comment by AxelHamburch** [comment]
Even if I want to add or delete something afterwards, the update only happens when I change the type (POS, ATM, Switch) or the currency.

**Comment by AxelHamburch** [comment]
Setting several at the same time does not seem to work either.

![2023-04-03 17_24_09-LNbits🍺](https://user-images.githubusercontent.com/84231978/229555427-b670ea29-e0ab-478f-96ea-97105a42673e.png)

**Comment by dni** [comment]
weird, it should not be called profit anymore inside latest. did you hard reload the page? maybe some cache issue?

**Comment by AxelHamburch** [comment]
Ich habe noch mal ein `git pull` gemacht und jetzt funktioniert es. Der Issue kann also geschlossen werden. Danke!
